version: "3.9"

services:
  db:
    image: postgres:16
    container_name: pg-restaurant-service
    environment:
      POSTGRES_USER: restaurant
      POSTGRES_PASSWORD: restaurant
      POSTGRES_DB: pg-restaurant-service
    ports:
      - "5432:5432"
    volumes:
      - pg-restaurant-service-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://restaurant:restaurant@db:5432/pg-restaurant-service
    depends_on:
      - db

volumes:
  pg-restaurant-service-data:
    driver: local
