docker_build("restaurant-image", ".", dockerfile="./Dockerfile")

yaml = helm(
    "../../deployment/charts/base",
    name="restaurant-release",
    values=["../../deployment/kubernetes/restaurant_service/values.yaml"],
)
k8s_yaml(yaml)

# deploy the PostgreSQL Helm chart
# postgres_yaml = helm(
#     "../../deployment/charts/postgresql",
#     name="restaurant-release-postgresql",
#     values=["../../deployment/kubernetes/restaurant_service/postgresql-values.yaml"],
# )
# k8s_yaml(postgres_yaml)

k8s_resource("restaurant-pg", port_forwards=5432)

k8s_resource("restaurant-service", port_forwards=3000)
