docker_build("restaurant-image", ".", dockerfile="./Dockerfile")

yaml = helm(
    "../../deployment/charts/base",
    name="booking-release",
    values=["../../deployment/kubernetes/restaurant_service/values.yaml"],
)
k8s_yaml(yaml)


k8s_resource("restaurant", port_forwards=8001)
