app_name: notification-service
image: mslaursen/notification-service:0.3
container_port: 8001
namespace: default

replicaCount: 1

env: 
  NOTIFICATION_SERVICE_HOST: "0.0.0.0"
  NOTIFICATION_SERVICE_PORT: 8001
  NOTIFICATION_SERVICE_WORKERS: 1
  NOTIFICATION_SERVICE_LOG_LEVEL: info
  NOTIFICATION_SERVICE_MAILGUN_API_KEY: 12402db5f7a58c0f3394b2eed96f1369-2e68d0fb-3426e34e
  NOTIFICATION_SERVICE_MAILGUN_DOMAIN:  sandbox4a57df30840c414fb847322bf96d64f0.mailgun.org
  NOTIFICATION_SERVICE_MAILGUN_FROM_EMAIL: mailgun@sandbox4a57df30840c414fb847322bf96d64f0.mailgun.org

resources:
  requests:
    memory: "128Mi"
    cpu: "500m"
  limits:
    memory: "256Mi"
    cpu: "1"
