app_name: notification-service
image: notification-image
container_port: 8000
namespace: default

replicaCount: 1

env: 
  NOTIFICATION_SERVICE_HOST: "0.0.0.0"
  NOTIFICATION_SERVICE_PORT: 8001
  NOTIFICATION_SERVICE_WORKERS: 1
  NOTIFICATION_SERVICE_LOG_LEVEL: info

resources:
  requests:
    memory: "128Mi"
    cpu: "500m"
  limits:
    memory: "256Mi"
    cpu: "1"
