app_name: example
image: example-image
container_port: 8000
namespace: default

env:
  example_service_host: booking
  example_service_port: 8000
  example_service_workers: "1"
  example_service_log_level: "info"
  example_service_reload: "true"

resources:
  requests:
    memory: "128Mi"
    cpu: "500m"
  limits:
    memory: "256Mi"
    cpu: "1"
