version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: pg-restaurant-service
    environment:
      POSTGRES_USER: restaurant
      POSTGRES_PASSWORD: restaurant
      POSTGRES_DB: pg-restaurant-service
    ports:
      - "5432:5432"
    volumes:
      - pg-restaurant-service-data:/var/lib/postgresql/data

volumes:
  pg-restaurant-service-data:
    driver: local
