app_name: auth-service
image: mslaursen/auth-service:0.2
container_port: 8002
namespace: default

replicaCount: 1

env: 
  AUTH_SERVICE_ENVIRONMENT: "dev"
  AUTH_SERVICE_HOST: "0.0.0.0"
  AUTH_SERVICE_PORT: 8002
  AUTH_SERVICE_WORKERS: 1
  AUTH_SERVICE_LOG_LEVEL: info
  AUTH_SERVICE_JWT_SECRET: yo

  AUTH_SERVICE_PG_HOST: "pg-kea-bachelor-auth.postgres.database.azure.com"
  AUTH_SERVICE_PG_PORT: 5432
  AUTH_SERVICE_PG_USER: "bachelor@pg-kea-bachelor-auth"
  AUTH_SERVICE_PG_PASSWORD: "P@ssw0rd"
  AUTH_SERVICE_PG_DB: "auth-db"
  AUTH_SERVICE_PG_POOL_SIZE: 15
  AUTH_SERVICE_PG_ECHO: false

  AUTH_SERVICE_PG_RO_HOST: "pg-kea-bachelor-auth-replica-1.postgres.database.azure.com"
  AUTH_SERVICE_PG_RO_PORT: 5432
  AUTH_SERVICE_PG_RO_USER: "bachelor@pg-kea-bachelor-auth-replica-1"
  AUTH_SERVICE_PG_RO_PASSWORD: "P@ssw0rd"
  AUTH_SERVICE_PG_RO_DB: "auth-db"
  AUTH_SERVICE_PG_RO_POOL_SIZE: 15
  AUTH_SERVICE_PG_RO_ECHO: false


resources:
  requests:
    memory: "128Mi"
    cpu: "500m"
  limits:
    memory: "256Mi"
    cpu: "1"
