app_name: restaurant-service
image: restaurant-image
container_port: 3000

env: 
  restaurant_service_host: "0.0.0.0"
  restaurant_service_port: 3000
  restaurant_service_workers: "1"
  restaurant_service_log_level: "info"
  restaurant_service_reload: "true"
  restaurant_database_url: "postgresql://postgres:postgres@restaurant-pg:5432/pg-restaurant-service"
  restaurant_es_url: "http://elasticsearch:9200"
  restaurant_rabbit_hostname: "rabbitmq"
  restaurant_rabbit_port: 5672
  restaurant_rabbit_username: "user"
  restaurant_rabbit_password: "password"
  node_env: "DEV"

resources:
  requests:
    memory: "128Mi"
    cpu: "500m"
  limits:
    memory: "256Mi"
    cpu: "1"

autoscaling:
  enabled: false

postgresql:
  enabled: true
  fullnameOverride: restaurant-pg
  architecture: standalone
  auth:
    postgresPassword: postgres
    username: postgres
    password: postgres
    database: pg-restaurant-service

