app_name: restaurant-service
image: mslaursen/restaurant-service:0.7
container_port: 3000
namespace: default

env: 
  restaurant_service_host: "0.0.0.0"
  restaurant_service_port: 3000
  restaurant_service_workers: "1"
  restaurant_service_log_level: "info"
  restaurant_service_reload: "true"
  restaurant_database_url: "postgresql://bachelor@pg-kea-bachelor-restaurant:P@ssw0rd@pg-kea-bachelor-restaurant.postgres.database.azure.com:5432/restaurant-db"
  restaurant_es_url: "http://elasticsearch:9200"
  restaurant_rabbit_hostname: "rabbitmq"
  restaurant_rabbit_port: 5672
  restaurant_rabbit_username: "user"
  restaurant_rabbit_password: "password"
  node_env: "PROD"
resources:
  requests:
    memory: "128Mi"
    cpu: "500m"
  limits:
    memory: "256Mi"
    cpu: "1"
