app_name: restaurant
image: restaurant-image
container_port: 3000

env: 
  restaurant_service_host: "0.0.0.0"
  restaurant_service_port: 3000
  restaurant_service_workers: "1"
  restaurant_service_log_level: "info"
  restaurant_service_reload: "true"
  restaurant_database_url: "postgresql://postgres:postgres@restaurant-pg-primary:5432/pg-restaurant-service"
  node_env: "DEV"

resources:
  requests:
    memory: "256Mi"
    cpu: "1000m"
  limits:
    memory: "512Mi"
    cpu: "2"

autoscaling:
  enabled: false

postgresql:
  enabled: true
  fullnameOverride: restaurant-pg
  architecture: replication
  auth:
    postgresPassword: postgres
    username: postgres
    password: postgres
    database: pg-restaurant-service

    replicationUsername: postgres_repl
    replicationPassword: postgres_repl

  readReplicas:
    replicaCount: 1

elasticsearch:
  enabled: false
  replicaCount: 0
  minimumMasterNodes: 1
  persistence:
    enabled: true
    size: 10Gi
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 0.5
      memory: 1Gi