load("ext://helm_resource", "helm_resource", "helm_repo")

helm_resource(
    name="keycloak",
    chart="bitnami/keycloak",
    flags=["--values=./values.yaml"],
)

local_resource(
    "kc-pf",
    serve_cmd="kubectl port-forward service/keycloak 8090:80",
)
