docker_build("auth-image", ".", dockerfile="./Dockerfile")

yaml = helm(
    "../../deployment/charts/base",
    name="auth-release",
    values=["../../deployment/kubernetes/auth_service/values.yaml"],
)
k8s_yaml(yaml)


k8s_resource("auth-service", port_forwards=8002)
