load("ext://helm_resource", "helm_resource", "helm_repo")

helm_resource(
    name="rabbitmq",
    chart="bitnami/rabbitmq",
    flags=["--values=./values.yaml"],
)   

local_resource(
    "rabbitmq-pf",
    serve_cmd="kubectl port-forward service/rabbitmq 15672:15672",
)