apiVersion: v1
kind: Service
metadata:
  name: booking-svc
  labels:
    app: booking-svc
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: booking-svc
