app_name: booking-service
image: booking-image
container_port: 8000

replicaCount: 1

env: 
  BOOKING_SERVICE_HOST: "0.0.0.0"
  BOOKING_SERVICE_PORT: 8000
  BOOKING_SERVICE_WORKERS: 1
  BOOKING_SERVICE_LOG_LEVEL: info

  BOOKING_SERVICE_PG_HOST: "booking-release-postgresql-primary"
  BOOKING_SERVICE_PG_PORT: 5432
  BOOKING_SERVICE_PG_USER: "postgres"
  BOOKING_SERVICE_PG_PASSWORD: "postgres"
  BOOKING_SERVICE_PG_DB: "booking-db"
  BOOKING_SERVICE_PG_POOL_SIZE: 15
  BOOKING_SERVICE_PG_ECHO: false

  BOOKING_SERVICE_PG_RO_HOST: "booking-release-postgresql-read"
  BOOKING_SERVICE_PG_RO_PORT: 5432
  BOOKING_SERVICE_PG_RO_USER: "postgres_repl"
  BOOKING_SERVICE_PG_RO_PASSWORD: "postgres_repl"
  BOOKING_SERVICE_PG_RO_DB: "booking-db"
  BOOKING_SERVICE_PG_RO_POOL_SIZE: 15
  BOOKING_SERVICE_PG_RO_ECHO: false

resources:
  requests:
    memory: "128Mi"
    cpu: "500m"
  limits:
    memory: "256Mi"
    cpu: "1"

postgresql:
  enabled: true
  fullnameOverride: booking-pg
  architecture: replication
  auth:
    postgresPassword: postgres
    username: postgres
    password: postgres
    database: booking-db

    replicationUsername: postgres_repl
    replicationPassword: postgres_repl

  readReplicas:
    replicaCount: 1
    
elasticsearch:
  enabled: false