app_name: booking
image: booking-image
container_port: 8000
namespace: default

env: 
  booking_service_host: "0.0.0.0"
  booking_service_port: 8000
  booking_service_workers: "1"
  booking_service_log_level: "info"
  booking_service_reload: "true"

resources:
  requests:
    memory: "128Mi"
    cpu: "500m"
  limits:
    memory: "256Mi"
    cpu: "1"