app_name: booking-service
image: mslaursen/booking-service:0.5
container_port: 8000
namespace: default

replicaCount: 1

env: 
  BOOKING_SERVICE_ENVIRONMENT: "dev"
  BOOKING_SERVICE_HOST: "0.0.0.0"
  BOOKING_SERVICE_PORT: 8000
  BOOKING_SERVICE_WORKERS: 1
  BOOKING_SERVICE_LOG_LEVEL: info

  BOOKING_SERVICE_PG_HOST: "pg-kea-bachelor-booking.postgres.database.azure.com"
  BOOKING_SERVICE_PG_PORT: 5432
  BOOKING_SERVICE_PG_USER: "bachelor@pg-kea-bachelor-booking"
  BOOKING_SERVICE_PG_PASSWORD: "P@ssw0rd"
  BOOKING_SERVICE_PG_DB: "booking-db"
  BOOKING_SERVICE_PG_POOL_SIZE: 15
  BOOKING_SERVICE_PG_ECHO: false

  BOOKING_SERVICE_PG_RO_HOST: "pg-kea-bachelor-booking.postgres.database.azure.com"
  BOOKING_SERVICE_PG_RO_PORT: 5432
  BOOKING_SERVICE_PG_RO_USER: "bachelor@pg-kea-bachelor-booking"
  BOOKING_SERVICE_PG_RO_PASSWORD: "P@ssw0rd"
  BOOKING_SERVICE_PG_RO_DB: "booking-db"
  BOOKING_SERVICE_PG_RO_POOL_SIZE: 15
  BOOKING_SERVICE_PG_RO_ECHO: false

resources:
  requests:
    memory: "128Mi"
    cpu: "500m"
  limits:
    memory: "256Mi"
    cpu: "1"
