docker_build("booking-image", ".", dockerfile="./Dockerfile")

yaml = helm(
    "../../deployment/charts/base",
    name="notification-release",
    values=["../../deployment/kubernetes/notification_service/values.yaml"],
)
k8s_yaml(yaml)


k8s_resource("notificationservice", port_forwards=8001)
