docker_build("booking-image", ".", dockerfile="./Dockerfile")

yaml = helm(
    "../../deployment/charts/base",
    name="booking-release",
    values=["../../deployment/kubernetes/booking_service/values.yaml"],
)
k8s_yaml(yaml)


k8s_resource("booking-service", port_forwards=8000)
