docker_build("booking-svc-image", ".", dockerfile="./Dockerfile")

k8s_yaml(
    [
        "../../deployment/kubernetes/booking_service/deployment.yaml",
        "../../deployment/kubernetes/booking_service/service.yaml",
    ]
)

k8s_resource("booking-svc", port_forwards=8000)
