docker_build("booking-service-image", ".", dockerfile="./Dockerfile")

k8s_yaml(
    [
        "../../deployment/kubernetes/booking_service/deployment.yaml",
        "../../deployment/kubernetes/booking_service/service.yaml",
    ]
)

k8s_resource("booking-depl", port_forwards=8010)
