postgresql:
  auth:
    username: ai
    password: ai
    database: pg-ai-service
  primary:
    initContainers:
    - name: install-pgvector
      image: bitnami/postgresql:17
      command: 
      - /bin/sh
      - -c
      - |
        set -ex
        apt-get update
        apt-get install -y \
          postgresql-contrib \
          postgresql-server-dev-all \
          build-essential \
          git \
          make \
          gcc
        git clone --branch v0.6.2 https://github.com/pgvector/pgvector.git
        cd pgvector
        make
        make install
      securityContext:
        runAsUser: 0
  
  initdbScripts:
    create-vector-extension.sql: |
      CREATE EXTENSION IF NOT EXISTS vector;

  extendedConfiguration: |
    shared_preload_libraries = 'vector.so'