app_name: ai-service
image: ai-image
container_port: 8089

env: 
  ai_service_host: "0.0.0.0"
  ai_service_port: 8089
  ai_service_workers: "1"
  ai_service_log_level: "info"
  ai_service_reload: "true"
  ai_database_url: "postgresql+asyncpg://postgres:postgres@ai-release-postgresql-primary:5432/pg-ai-service"
  ai_openai_azure_key: "FIgB5D8SRxuQaLKTzc92pFjwfs8eJfAAH5pUCigcl8J0xrbkXrqsJQQJ99AKACfhMk5XJ3w3AAABACOGGbGL"
  ai_openai_azure_endpoint: "https://ai-skynet.openai.azure.com/openai/deployments/gpt-4/chat/completions?api-version=2024-08-01-preview"
  ai_embedding_azure_key: "FIgB5D8SRxuQaLKTzc92pFjwfs8eJfAAH5pUCigcl8J0xrbkXrqsJQQJ99AKACfhMk5XJ3w3AAABACOGGbGL"
  ai_embedding_azure_endpoint: "https://ai-skynet.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15"
  ai_embedding_azure_model: "text-embedding-ada-002"
  ai_elasticsearch_url: "http://elasticsearch:9200"
  ai_rabbit_hostname: "rabbitmq"
  ai_rabbit_port: 5672
  ai_rabbit_username: "user"
  ai_rabbit_password: "password"

resources:
  requests:
    memory: "128Mi"
    cpu: "500m"
  limits:
    memory: "256Mi"
    cpu: "1"

autoscaling:
  enabled: true
