app_name: ai-service
image: mslaursen/ai-service:0.1
container_port: 8089
namespace: default

env: 
  ai_service_host: "0.0.0.0"
  ai_service_port: 8089
  ai_service_workers: "1"
  ai_service_log_level: "info"
  ai_service_reload: "true"
  ai_database_url: "postgresql+asyncpg://ai:ai@host.docker.internal:5434/pg-ai-service"
  AI_OPENAI_AZURE_KEY: "FIgB5D8SRxuQaLKTzc92pFjwfs8eJfAAH5pUCigcl8J0xrbkXrqsJQQJ99AKACfhMk5XJ3w3AAABACOGGbGL"
  AI_OPENAI_AZURE_ENDPOINT: "https://ai-skynet.openai.azure.com/openai/deployments/gpt-4/chat/completions?api-version=2024-08-01-preview"
  AI_EMBEDDING_AZURE_KEY: "FIgB5D8SRxuQaLKTzc92pFjwfs8eJfAAH5pUCigcl8J0xrbkXrqsJQQJ99AKACfhMk5XJ3w3AAABACOGGbGL"
  AI_EMBEDDING_AZURE_ENDPOINT: "https://ai-skynet.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15"
  AI_EMBEDDING_AZURE_MODEL: "text-embedding-ada-002"
  
resources:
  requests:
    memory: "128Mi"
    cpu: "500m"
  limits:
    memory: "256Mi"
    cpu: "1"
