apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-route
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/plugins: rate-limit
spec:
  parentRefs:
  - name: kong
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /booking-service
    backendRefs:
    - name: booking
      kind: Service
      port: 80

