apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-route
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/plugins: rate-limit, custom-keycloak-jwt
spec:
  parentRefs:
  - name: kong
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /booking-service
    backendRefs:
    - name: booking
      kind: Service
      port: 80
---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: http-route
#   annotations:
#     konghq.com/strip-path: "true"
# spec:
#   parentRefs:
#   - name: kong
#   rules:
#   - matches:
#     - path:
#         type: PathPrefix
#         value: /keycloak
#     backendRefs:
#     - name: keycloak
#       kind: Service
#       port: 80

