apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limit
  annotations:
    kubernetes.io/ingress.class: kong
config:
  minute: 10
  policy: local
plugin: rate-limiting
---
# apiVersion: configuration.konghq.com/v1
# kind: KongPlugin
# metadata:
#   name: custom-keycloak-jwt
# config:
#   keycloak_introspection_url: "http://localhost:8090/realms/bachelor/protocol/openid-connect/token/introspect"
#   client_id: "introspection-client"
#   client_secret: "**********"
# plugin: custom-keycloak-jwt
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: custom-authsvc-jwt
config:
  current_user_url: "http://auth-service/api/v1/auth/users/me"
plugin: custom-authsvc-jwt

