load("ext://helm_resource", "helm_resource", "helm_repo")

helm_repo(
    name="kong", 
    url="https://charts.konghq.com"
)
helm_resource(
    name="kong-ingress", 
    chart="kong/ingress", 
    flags=["--values=./values.yaml"],
)

# install gateway api CRDs
gateway_api_yaml = local(
    command="curl -sL https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml",
    quiet=True,
    echo_off=True,
)

k8s_yaml(gateway_api_yaml)

# kong ingress manifests just sends commands to the ingress-gateway,
# so these won't show up in the tilt ui
k8s_yaml(
    [
        "./gateway_class.yaml",
        "./gateway.yaml",
        "./http_route.yaml",
    ]
)