replicaCount: 1

admin:
  enabled: true
  type: NodePort

  tls:
    enabled: false
    
  http:
    enabled: true

proxy:
  labels:
    enabled: "false"

plugins:
  configMaps:
  - name: custom-authsvc-jwt
    pluginName: custom-authsvc-jwt